In [4]:
# pandas, numpy, seaborn, matplotlib, scikit-learn
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# sklearn preprocessing tools: StandardScaler, MinMaxScaler, LabelEncoder, OneHotEncoder
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder, OneHotEncoder
#  sklearn imputer: SimpleImputer
from sklearn.impute import SimpleImputer

# Display settings
plt.style.use('seaborn-v0_8-darkgrid')
%matplotlib inline
pd.set_option('display.max_columns', 20)
pd.set_option('display.max_rows', 100)

In [5]:
import seaborn as sns
# === LOAD THE DATA ===
# Load Titanic dataset from seaborn
# Save as titanic_raw - this is our Original backup copy of the data
titanic_raw = sns.load_dataset('titanic')

In [6]:
# === FIRST LOOK AT THE DATA ===
# Display the first 10 rows of the dataset
titanic_raw.head(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False

In [7]:
# === ESSENTIAL WORKFLOW ===
#  shape - how big is the data?
print("Shape of the dataset:", titanic_raw.shape)

Shape of the dataset: (891, 15)

In [8]:
# info() - what are the data types and non-null counts (what's missing?)
print(titanic_raw.info())

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB
None

In [9]:
# describe - what are the summary statistics for numeric columns?
print(titanic_raw.describe())

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [10]:
# === STEP 1: CHECK FOR DUPLICATES ===
#  create working copy: df = titanic_raw.copy()
# count duplicates : df.duplicated().sum()
df = titanic_raw.copy()
df = df.drop_duplicates()
print(f"Duplicate rows: {df.duplicated().sum()}")
print(f"Rows after removing duplicates: {df.shape}")

Duplicate rows: 0
Rows after removing duplicates: (784, 15)

In [11]:
# EXAMPLE : what duplicates look like
duplicates_df = df[df.duplicated(keep=False)]
duplicates_df

Empty DataFrame
Columns: [survived, pclass, sex, age, sibsp, parch, fare, embarked, class, who, adult_male, deck, embark_town, alive, alone]
Index: []

In [12]:
df.sort_values(['pclass','who']).head(20)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
297,0,1,female,2.00,1,2,151.5500,S,First,child,False,C,Southampton,no,False
305,1,1,male,0.92,1,2,151.5500,S,First,child,False,C,Southampton,yes,False
435,1,1,female,14.00,1,2,120.0000,S,First,child,False,B,Southampton,yes,False
445,1,1,male,4.00,0,2,81.8583,S,First,child,False,A,Southampton,yes,False
689,1,1,female,15.00,0,1,211.3375,S,First,child,False,B,Southampton,yes,False
802,1,1,male,11.00,1,2,120.0000,S,First,child,False,B,Southampton,yes,False
6,0,1,male,54.00,0,0,51.8625,S,First,man,True,E,Southampton,no,True
23,1,1,male,28.00,0,0,35.5000,S,First,man,True,A,Southampton,yes,True
27,0,1,male,19.00,3,2,263.0000,S,First,man,True,C,Southampton,no,False
30,0,1,male,40.00,0,0,27.7208,C,First,man,True,NaN,Cherbourg,no,True
34,0,1,male,28.00,1,0,82.1708,C,First,man,True,NaN,Cherbourg,no,False
35,0,1,male,42.00,1,0,52.0000,S,First,man,True,NaN,Southampton,no,False
54,0,1,male,65.00,0,1,61.9792,C,First,man,True,B,Cherbourg,no,False
55,1,1,male,NaN,0,0,35.5000,S,First,man,True,C,Southampton,yes,True
62,0,1,male,45.00,1,0,83.4750,S,First,man,True,C,Southampton,no,False
64,0,1,male,NaN,0,0,27.7208,C,First,man,True,NaN,Cherbourg,no,True
83,0,1,male,28.00,0,0,47.1000,S,First,man,True,NaN,Southampton,no,True
92,0,1,male,46.00,1,0,61.1750,S,First,man,True,E,Southampton,no,False
96,0,1,male,71.00,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
97,1,1,male,23.00,0,1,63.3583,C,First,man,True,D,Cherbourg,yes,False

In [14]:
# === REMOVE DUPLICATES ===
#  Use drop_duplicates() to remove duplicates
# Show before/after row counts
print(f"Rows before removing duplicates: {df.shape}")
clean_data = df.drop_duplicates()
print(f"Rows after removing duplicates: {clean_data.shape}")

Rows before removing duplicates: (784, 15)
Rows after removing duplicates: (784, 15)

In [15]:
print(f"Rows after removing duplicates: {df.shape}")

Rows after removing duplicates: (784, 15)

In [16]:
# === DUPLICATES ON SPECIFIC COLUMNS ===
# Check for duplicates based on 'pclass' and 'who'
duplicate_subset = df.duplicated(subset=['pclass', 'who'])
# Keep first or last occurrence
print(f"Duplicate rows based on 'pclass' and 'who': {duplicate_subset.sum()}")

Duplicate rows based on 'pclass' and 'who': 775

In [17]:
print(df.info())

<class 'pandas.DataFrame'>
Index: 784 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     784 non-null    int64
 1   pclass       784 non-null    int64
 2   sex          784 non-null    str
 3   age          678 non-null    float64
 4   sibsp        784 non-null    int64
 5   parch        784 non-null    int64
 6   fare         784 non-null    float64
 7   embarked     782 non-null    str
 8   class        784 non-null    category
 9   who          784 non-null    str
 10  adult_male   784 non-null    bool
 11  deck         202 non-null    category
 12  embark_town  782 non-null    str
 13  alive        784 non-null    str
 14  alone        784 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 77.0 KB
None

In [18]:
# === STEP 2: MISSING VALUES ANALYSIS ===
# Count missing values: df.isnull().sum()
# Calculate missing percentage: (df.isnull().sum() / len(df)) * 100
import pandas as pd

missing_counts = clean_data.isnull().sum()
missing_pct = (missing_counts / len(df)) * 100
missing_df = pd.DataFrame(
    {
        'Missing Count': missing_counts,
        'Missing Percentage': missing_pct
    }
)
# print(missing_df)

missing_df[missing_df['Missing Count'] > 0]

             Missing Count  Missing Percentage
age                    106           13.520408
embarked                 2            0.255102
deck                   582           74.234694
embark_town              2            0.255102

In [19]:
# === STEP 2a: DROP SPARSE COLUMNS ===
# Drop columns with more than 50% missing values
# Drop 'deck' column (77% missing)
import pandas as pd
print(f"Number of columns before dropping sparse columns: {len(df.columns)}")
df = df.drop(columns=['deck'])
print(f"Number of columns after dropping sparse columns: {len(df.columns)}")

Number of columns before dropping sparse columns: 15
Number of columns after dropping sparse columns: 14

In [20]:
df.info()

<class 'pandas.DataFrame'>
Index: 784 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     784 non-null    int64
 1   pclass       784 non-null    int64
 2   sex          784 non-null    str
 3   age          678 non-null    float64
 4   sibsp        784 non-null    int64
 5   parch        784 non-null    int64
 6   fare         784 non-null    float64
 7   embarked     782 non-null    str
 8   class        784 non-null    category
 9   who          784 non-null    str
 10  adult_male   784 non-null    bool
 11  embark_town  782 non-null    str
 12  alive        784 non-null    str
 13  alone        784 non-null    bool
dtypes: bool(2), category(1), float64(2), int64(4), str(5)
memory usage: 75.9 KB

# SimpleImputer: The Professional Approach to Handling Missing Data
WHY USE SimpleImputer INSTEAD OF fillna()?

fillna() is great for quick exploratory work.
SimpleImputer is designed for production-ready data preprocessing because :

1. CONSISTENCY: SimpleImputer ensures the same imputation strategy is applied across all datasets (train, test, new data) by fitting on the training data and transforming consistently. It remembers the imputation values, preventing data leakage and ensuring reproducibility.

2. PIPELINE INTEGRATION: SimpleImputer can be seamlessly integrated into scikit-learn pipelines, allowing for streamlined preprocessing and model training in a single workflow.

3. options: SimpleImputer offers various imputation strategies (mean, median, most_frequent, constant) and can handle both numerical and categorical data effectively.

In [21]:
# pandas, numpy, seaborn, matplotlib, scikit-learn
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# sklearn preprocessing tools: StandardScaler, MinMaxScaler, LabelEncoder, OneHotEncoder
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder, OneHotEncoder
#  sklearn imputer: SimpleImputer pip install scikit-learn
from sklearn.impute import SimpleImputer
# === STEP 2b: FILL AGE WITH SIMPLEIMPUTER ===
# Create SimpleImputer with strategy='median' for 'age' column
age_imputer = SimpleImputer(strategy='median')
# Fit and transform the 'age' column
df['age'] = age_imputer.fit_transform(df[['age']])
# CHECK IMPUTER.STATISTICS_ - this shows the median value used for imputation
print(f"Median age used for imputation: {age_imputer.statistics_[0]}")
# Verify that there are no more missing values in 'age'.
print(f"Missing values in 'age' after imputation: {df['age'].isnull().sum()}")

Median age used for imputation: 28.25
Missing values in 'age' after imputation: 0

In [22]:
df.info()

<class 'pandas.DataFrame'>
Index: 784 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     784 non-null    int64
 1   pclass       784 non-null    int64
 2   sex          784 non-null    str
 3   age          784 non-null    float64
 4   sibsp        784 non-null    int64
 5   parch        784 non-null    int64
 6   fare         784 non-null    float64
 7   embarked     782 non-null    str
 8   class        784 non-null    category
 9   who          784 non-null    str
 10  adult_male   784 non-null    bool
 11  embark_town  782 non-null    str
 12  alive        784 non-null    str
 13  alone        784 non-null    bool
dtypes: bool(2), category(1), float64(2), int64(4), str(5)
memory usage: 75.9 KB

# Advanced: Group-Specific Imputation with SimpleImputer
Sometimes the overall median isn't the best choice for imputation, especially when different groups in the data have distinct distributions. In such cases, you can perform group-specific imputation using SimpleImputer.

In [23]:
# === GROUP IMPUTATION DEMO ===
# Show median age by passenger class (from original data)
titanic_raw.groupby('pclass')['age'].median()

pclass
1    37.0
2    29.0
3    24.0
Name: age, dtype: float64

In [24]:
# === GROUP IMPUTATION PATTERN ===
# Pattern: df.groupby('pclass')['age'].transform(lambda x: x.fillna(x.median()))
# This fills each missing value with median of its GROUP
df.groupby('pclass')['age'].transform(lambda x: x.fillna(x.median()))

0      22.00
1      38.00
2      26.00
3      35.00
4      35.00
       ...
885    39.00
887    19.00
888    28.25
889    26.00
890    32.00
Name: age, Length: 784, dtype: float64

In [25]:
# === STEP 2c: FILL CATEGORICAL COLUMNS ===
# Fill embarked and embark_town with mode (most common value)
# df['col'].mode()[0] gives most frequent value

print(f"Embarked missing before: {df['embarked'].isnull().sum()}")
print(f"Embarked Town missing before: {df['embark_town'].isnull().sum()}")

df['embarked'] = df['embarked'].fillna(df['embarked'].mode()[0])
df['embark_town'] = df['embark_town'].fillna(df['embark_town'].mode()[0])

print(f"Embarked missing before: {df['embarked'].isnull().sum()}")
print(f"Embarked Town missing before: {df['embark_town'].isnull().sum()}")

Embarked missing before: 2
Embarked Town missing before: 2
Embarked missing before: 0
Embarked Town missing before: 0

In [28]:
# === VERIFY: No Missing Values ===
# Check remaining missing values

df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

## What we've covered:
```
The 6-step preprocessing pipeline (memorize this order!)
Duplicate detection and removal
Missing value strategies: drop, impute with median/mode, group imputation
SimpleImputer for production ML pipelines

Feature Engineering - Creating powerful new features from existing data
```

## Part 3: Feature Engineering
Creating New Information from Existing Data

In [29]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'embark_town', 'alive',
       'alone'],
      dtype='str')

In [30]:
# === STEP 3: FEATURE ENGINEERING ===
# Look at family columns: sibsp (siblings/spouses) and parch (parents/children)
# Create new feature 'family_size' = sibsp + parch + 1 (include self)
df[['sibsp', 'parch']].head(10)

   sibsp  parch
0      1      0
1      1      0
2      0      0
3      1      0
4      0      0
5      0      0
6      0      0
7      3      1
8      0      2
9      1      0

In [32]:
# === CREATE FAMILY_SIZE ===
# family_size = sibsp + parch + 1 (include the passenger)
# Check the distribution
df['family_size'] = df['sibsp'] + df['parch'] + 1
df['family_size'].value_counts().sort_index()

family_size
1     446
2     154
3     101
4      28
5      13
6      22
7      12
8       6
11      2
Name: count, dtype: int64

In [33]:
# === THE PAYOFF: Survival by Family Size ===
# df.groupby('family_size')['survived'].mean()
# What patterns do you see?
survival_by_family = df.groupby('family_size')['survived'].mean() * 100
survival_by_family

family_size
1     33.632287
2     55.194805
3     57.425743
4     71.428571
5     23.076923
6     13.636364
7     33.333333
8      0.000000
11     0.000000
Name: survived, dtype: float64

In [38]:
# === CREATE IS_ALONE ===
# Binary feature: 1 if family_size == 1, else 0
# Compare survival rates: alone vs with family

df['is_alone'] = (df['family_size'] == 1).astype(int)

print(f"Alone: {df[df['is_alone'] == 1]['survived'].mean()*100}%")
print(f"With Family: {df[df['is_alone'] == 0]['survived'].mean()*100}%")

Alone: 33.6322869955157%
With Family: 51.183431952662716%

In [41]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'embark_town', 'alive',
       'alone', 'family_size', 'is_alone'],
      dtype='str')

In [43]:
# === LOOK AT NAME COLUMN ===
# Pattern: "Lastname, Title. Firstname"
# What titles can you spot?
df['name'].head(10)

0      man
1    woman
2    woman
3    woman
4      man
5      man
6      man
7    child
8    woman
9    child
Name: who, dtype: str

In [ ]:
# === EXTRACT TITLE WITH REGEX ===
# df['name'].str.extract(r',\s*([^.]+)\.')
# Check value_counts() of extracted titles

df['title'] = df['Name'].str.extract(r',\s*([^.]+)\.')

df['title'].value_counts()

In [ ]:
# === SIMPLIFY TITLES ===
# Create mapping: common titles stay, rare ones become 'Rare'
# Mlle -> Miss, Mme -> Mrs

title_mapping = {
    'Mr': 'Mr',
    'Miss': 'Miss',
    'Mrs': 'Mrs',
    'Master': 'Master',
    # map rare/foreign titles
    'Dr': 'Rare',
    'Rev': 'Rare',
    'Col': 'Rare',
    'Mlle': 'Miss',
    'Major': 'Rare',
    'Ms': 'Mrs',
    'Mme': 'Mrs',
    'Don': 'Rare',
    'Lady': 'Rare',
    'Sir': 'Rare',
    'Capt': 'Rare',
    'the Countess': 'Rare',
    'Jonkheer': 'Rare'
}

df['title'] = df['title'].map(title_mapping)
df['title']

In [ ]:
# === THE PAYOFF: Survival by Title ===
# df.groupby('title')['survived'].mean()
# Which titles had best/worst survival?

survival_by_title = df.groupby('title')['Survived'].mean() * 100

survival_by_title

In [ ]:
# === CREATE AGE GROUPS ===
bins = [0, 12, 18, 35, 60, 100]
labels = ['Child', 'Teen', 'Young Adult', 'Middle Aged', 'Senior']
df['age_group'] = pd.cut(df['Age'], bins=bins, labels=labels)

In [ ]:
# === SURVIVAL BY AGE GROUP ===
survival_by_age = df.groupby('age_group')['Survived'].mean() * 100
survival_by_age

# === STEP 3 SUMMARY ===
# Print features created

Feature Engineering Summary
COMMON FEATURE ENGINEERING TECHNIQUES:

| TECHNIQUE          | EXAMPLE                                  |
|--------------------|------------------------------------------|
| Combine columns    | family_size = sibsp + parch + 1          |
| Extract from text  | title = extract from name with regex     |
| Bin continuous     | age_group = pd.cut(age, bins, labels)    |
| Binary indicator   | is_alone = (family_size == 1)            |
| Mathematical       | fare_per_person = fare / family_size     |
| Date extraction    | month = date.dt.month, day_of_week       |

THE KEY INSIGHT:
Feature engineering is where DOMAIN KNOWLEDGE meets DATA.

Part 4: Outlier Detection and Handling

Finding and Treating Extreme Values

In [ ]:
# STEP 4: Outlier Detection
print("STEP 4: Outlier Detection and Handling")
print("=" * 40)

# Visualize distributions with boxplots
fig, axes = plt.subplots(1, 2, figsize=(12, 4))

axes[0].boxplot(df['Age'].dropna())
axes[0].set_title('Age Distribution')
axes[0].set_ylabel('Age (years)')

axes[1].boxplot(df['Fare'].dropna())
axes[1].set_title('Fare Distribution')
axes[1].set_ylabel('Fare ($)')

plt.tight_layout()
plt.show()

print("\nBoxplot interpretation:")
print(f"  Box = middle 50% of data (Q1 to Q3)")
print("  Line in box = median")
print("  Whiskers = 1.5 x IQR from box")
print("  Dots outside whiskers = OUTLIERS")

In [ ]:
# === EXAMINE FARE OUTLIERS ===
# Show fare statistics with describe()
# Show top 10 highest fares

print(df['Fare'].describe())

print(df.nlargest(10, 'Fare')[['Name', 'Pclass', 'Fare']])